### ISSUE TITLE
Render Screen Crash

### ISSUE THREAD

**Issue by Ac1dSn0w** [Funwayguy/RecipeResearch#1]
You probably figure it out when playing around with Recipe Research.

"Practice thus make improvement, but never makes perfect."    - Ac1dSn0w

Crash Log: http://pastebin.com/pCPPfbTH

**Comment by Funwayguy** [comment]
Yup... I made a stupid mistake/oversight. I assume you tried putting a blank research page in the table and then KABOOM!

**Comment by Funwayguy** [comment]
Fixed for next update
